# Generated by Django 5.1.4 on 2024-12-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='Category Title')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='Title in Url')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active / Inactive')),
                ('is_delete', models.BooleanField(verbose_name='Deleted / Not Deleted')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Product Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='Product Image')),
                ('short_description', models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='Product Short Description')),
                ('description', models.TextField(db_index=True, verbose_name='Product Description')),
                ('price', models.IntegerField(verbose_name='Product Price')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active / Inactive')),
                ('is_delete', models.BooleanField(verbose_name='Deleted / Not Deleted')),
                ('category', models.ManyToManyField(related_name='product_categories', to='product_module.productcategory', verbose_name='Product Categories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
