# Generated by Django 5.1.4 on 2024-12-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_productbrand_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(db_index=True, verbose_name='Product Price')),
                ('discount_percentage', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Discount Percentage')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='product_module.productprice', verbose_name='Product Price'),
        ),
    ]
