# Generated by Django 5.1.4 on 2024-12-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_productprice_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Product Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount Percentage'),
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
