# Generated by Django 5.1.4 on 2024-12-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_product_price_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount Percentage(If has discount)'),
        ),
    ]
