# Generated by Django 5.1.4 on 2024-12-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_productcategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
    ]
