# Generated by Django 5.1.4 on 2024-12-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='product_module.productcategory', verbose_name='Product Categories'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='images/product-gallery', verbose_name='Product Images'),
        ),
    ]
