# Generated by Django 5.1.4 on 2025-01-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_productcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomments',
            name='subject',
            field=models.CharField(default=1, max_length=100, verbose_name='Comment Subject'),
            preserve_default=False,
        ),
    ]
