# Generated by Django 5.1.4 on 2025-01-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_productcomments_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_categories', verbose_name='Image'),
        ),
    ]
