# Generated by Django 5.1.4 on 2025-01-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_productcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='image',
        ),
    ]
