# Generated by Django 5.1.4 on 2025-01-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_productvisits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvisits',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvisits', to='product_module.product', verbose_name='Product'),
        ),
    ]
