# Generated by Django 5.1.4 on 2025-01-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_alter_productvisits_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Discount End Time'),
        ),
    ]
