# Generated by Django 5.1.4 on 2025-01-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0017_product_discount_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscountTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Discount Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Discount End Time')),
            ],
            options={
                'verbose_name': 'Product Discount Timer',
                'verbose_name_plural': 'Product Discounts Timer',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_end_time',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_timer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product_module.productdiscounttimer', verbose_name='Discount Timer'),
        ),
    ]
