# Generated by Django 5.1.4 on 2025-01-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0018_productdiscounttimer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscounttimer',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active / Inactive'),
        ),
    ]
