# Generated by Django 5.1.4 on 2025-01-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0019_productdiscounttimer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscounttimer',
            name='is_active',
        ),
    ]
