# Generated by Django 5.1.4 on 2025-01-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0020_remove_productdiscounttimer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscounttimer',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted / Not deleted'),
        ),
    ]
