# Generated by Django 5.1.4 on 2025-01-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0021_productdiscounttimer_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/brands', verbose_name='Image'),
        ),
    ]
