# Generated by Django 5.1.4 on 2025-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0022_productbrand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscounttimer',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Main Discount'),
        ),
    ]
