# Generated by Django 5.1.4 on 2025-04-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0023_productdiscounttimer_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomments',
            name='subject',
        ),
    ]
