services:

  nginx:
    image: nginx:latest
    container_name: kala_nginx_server
    restart: always
    depends_on:
      - web
    ports:
      - "${NGINX_PORT}:15520"
    volumes:
      - "./.ci/nginx/conf.d:/etc/nginx/conf.d"
      - "static_volume:/app/staticfiles"
      - "media_volume:/app/media"
      
  redis:
    image: redis:7.4.2-alpine
    container_name: kala_redis

  db:
    image: postgres:latest
    container_name: kala_shop_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      retries: 5
      timeout: 5s

  web:
    build: .
    container_name: kala_django_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    volumes:
      - .:/app/
      - "static_volume:/app/staticfiles"
      - "media_volume:/app/media"
#    ports:
#      - "8000:8000"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build:
      context: .
      dockerfile: Dockerfile_Celery
    container_name: celery_worker
    environment:
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
    volumes:
      - .:/app/
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - redis
      - web
      - rabbitmq


  flower:
    image: mher/flower
    container_name: flower_server
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=redis://redis:6379/


volumes:
  postgres_data:
  static_volume:
  media_volume:
