FROM python:3.12

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --timeout=1000 -r requirements.txt

COPY . .

ENTRYPOINT ["celery", "--app=KalaMax_Project", "worker", "-l", "info", "-Q", "tasks,dead_letter", "-E"]
