# Generated by Django 5.1.4 on 2025-01-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='total_price',
            new_name='final_price',
        ),
    ]
