# Generated by Django 5.1.4 on 2025-01-11 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_rename_total_price_orderdetails_final_price'),
        ('product_module', '0022_productbrand_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetailss',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
