# Generated by Django 5.1.4 on 2025-01-11 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_rename_orderdetails_orderdetailss_and_more'),
        ('product_module', '0022_productbrand_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderDetailss',
            new_name='OrderDetails',
        ),
    ]
