# Generated by Django 5.1.4 on 2025-01-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0006_paymentmethod_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL'),
        ),
    ]
