# Generated by Django 5.1.4 on 2025-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0007_paymentmethod_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tracking Code'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='url',
            field=models.URLField(default='http://localhost:8000', max_length=300, verbose_name='URL'),
        ),
    ]
