# Generated by Django 5.1.4 on 2025-01-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0008_order_tracking_code_alter_paymentmethod_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_code',
        ),
    ]
