# Generated by Django 5.1.4 on 2025-01-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0009_remove_order_tracking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
