# Generated by Django 5.1.4 on 2025-01-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0010_remove_order_payment_method_delete_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tracking Code'),
        ),
    ]
