# Generated by Django 5.1.4 on 2025-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0012_alter_orderdetails_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tracking Code'),
        ),
    ]
