# Generated by Django 5.1.4 on 2024-12-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='images/sliders', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(max_length=300, verbose_name='URL')),
                ('is_active', models.BooleanField(verbose_name='Active / Inactive')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
