# Generated by Django 5.1.4 on 2024-12-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
    ]
