# Generated by Django 5.1.4 on 2025-01-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='country_and_city',
            field=models.CharField(default=1, max_length=200, verbose_name='Country/City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us_text',
            field=models.TextField(verbose_name='About Us text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copy_right',
            field=models.TextField(verbose_name='Site CopyRight text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='is_main_setting',
            field=models.BooleanField(verbose_name='Main Settings'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(upload_to='images/site-setting/', verbose_name='Site Logo'),
        ),
    ]
