# Generated by Django 5.1.4 on 2025-01-02 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0004_sitesettings_country_and_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_our_team',
            field=models.TextField(blank=True, null=True, verbose_name='About Our Team'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='Team Members'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_url',
            field=models.URLField(db_index=True, verbose_name='Site URL'),
        ),
    ]
