# Generated by Django 5.1.4 on 2025-01-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_sitesettings_about_our_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us_banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/site-setting', verbose_name='About Us Banner'),
        ),
    ]
