# Generated by Django 5.1.4 on 2025-01-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_alter_sitesettings_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_us_banner',
        ),
    ]
