# Generated by Django 5.1.4 on 2025-01-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_remove_sitesettings_about_us_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('url', models.URLField(blank=True, max_length=400, null=True, verbose_name='Url')),
                ('image', models.ImageField(upload_to='images/banners', verbose_name='Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active / Inactive')),
                ('position', models.CharField(choices=[('home_page', 'Home Page'), ('products_list', 'Products List Page'), ('about_us', 'About Us Page')], max_length=200, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Site Banner',
                'verbose_name_plural': 'Site Banners',
            },
        ),
    ]
