# Generated by Django 5.1.4 on 2025-01-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0011_alter_sitebanner_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=200, verbose_name='Question')),
                ('answer', models.TextField(db_index=True, verbose_name='Answer')),
                ('is_active', models.BooleanField(verbose_name='Active / Inactive')),
            ],
            options={
                'verbose_name': 'Frequently Answer Question',
                'verbose_name_plural': 'Frequently Answers Questions',
            },
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('home_page', 'Home Page'), ('discount_timer', 'Discount Timer'), ('faq', 'FAQ'), ('products_list', 'Products List Page'), ('about_us', 'About Us Page'), ('home_page_first', 'Home Page First Cat Image'), ('home_page_second', 'Home Page Second Cat Image'), ('home_page_third', 'Home Page Third Cat Image'), ('home_page_forth', 'Home Page Forth Cat Image')], max_length=200, verbose_name='Position'),
        ),
    ]
