# Generated by Django 5.1.4 on 2025-01-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0013_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_url', models.URLField(max_length=300, verbose_name='Twitter(X) Url')),
                ('instagram_url', models.URLField(max_length=300, verbose_name='Instagram Url')),
                ('github_url', models.URLField(max_length=300, verbose_name='GitHub Url')),
                ('is_main_urls', models.BooleanField(verbose_name='Is Main Urls / Is not Main Urls')),
            ],
        ),
    ]
