# Generated by Django 5.1.4 on 2025-01-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0014_sociallinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='social_urls',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_module.sociallinks', verbose_name='Social Urls'),
        ),
    ]
