# Generated by Django 5.1.4 on 2025-01-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0015_sitesettings_social_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
