# Generated by Django 5.1.4 on 2025-01-13 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0017_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('Text', models.TextField(verbose_name='Text')),
            ],
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_and_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_module.termsandconditions', verbose_name='Terms & Conditions'),
        ),
    ]
