# Generated by Django 5.1.4 on 2025-01-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0018_termsandconditions_sitesettings_terms_and_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termsandconditions',
            old_name='Text',
            new_name='text',
        ),
    ]
