# Generated by Django 5.1.4 on 2025-01-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0019_rename_text_termsandconditions_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('home_page', 'Home Page'), ('discount_timer', 'Discount Timer'), ('faq', 'FAQ'), ('terms_and_conditions', 'TermsAndConditions'), ('products_list', 'Products List Page'), ('about_us', 'About Us Page'), ('home_page_first', 'Home Page First Cat Image'), ('home_page_second', 'Home Page Second Cat Image'), ('home_page_third', 'Home Page Third Cat Image'), ('home_page_forth', 'Home Page Forth Cat Image')], max_length=200, verbose_name='Position'),
        ),
    ]
