# Generated by Django 5.1.4 on 2025-04-23 16:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0021_alter_sitebanner_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinks',
            name='twitter_url',
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text'),
        ),
    ]
