# Generated by Django 5.1.4 on 2024-12-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=200, verbose_name='Subject')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('message', models.TextField(verbose_name='Text')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('response', models.TextField(verbose_name='Response')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='Read / Unread')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us List',
            },
        ),
    ]
