# Generated by Django 5.1.4 on 2025-01-04 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('url_title', models.CharField(db_index=True, max_length=200, verbose_name='Url Title')),
                ('is_active', models.BooleanField(verbose_name='Active / Inactive')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blogs Categories',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('image', models.ImageField(upload_to='images/blog', verbose_name='Image')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('text', models.TextField(verbose_name='Text')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(verbose_name='Active / Inactive')),
                ('is_delete', models.BooleanField(verbose_name='Deleted / Not Deleted')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('categories', models.ManyToManyField(to='blog_module.blogcategory', verbose_name='Blog Categories')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
