# Generated by Django 5.1.4 on 2025-01-04 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0002_blogcategory_image_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=200, verbose_name='Caption')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tags', to='blog_module.blog', verbose_name='Related Blog')),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blogs Tags',
            },
        ),
    ]
