# Generated by Django 5.1.4 on 2025-01-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0003_blogtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted / Not Deleted'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted / Not Deleted'),
        ),
    ]
