# Generated by Django 5.1.4 on 2025-01-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0004_blogcategory_is_delete_alter_blog_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='short_description',
            field=models.CharField(default='', max_length=40, verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
