# Generated by Django 5.1.4 on 2025-01-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0005_blogcategory_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='short_description',
            field=models.CharField(max_length=45, verbose_name='Short Description'),
        ),
    ]
