# Generated by Django 5.1.4 on 2025-01-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0006_alter_blogcategory_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(related_name='blog_category', to='blog_module.blogcategory', verbose_name='Blog Categories'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Create Date'),
        ),
    ]
