# Generated by Django 5.1.4 on 2025-01-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0007_alter_blog_categories_alter_blog_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='create_time_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Time Date'),
        ),
    ]
