# Generated by Django 5.1.4 on 2025-01-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0009_alter_blog_create_time_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quotes',
            field=models.TextField(blank=True, null=True, verbose_name='Quotes'),
        ),
        migrations.CreateModel(
            name='BlogGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/blog_gallery')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_module.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Blog Gallery',
                'verbose_name_plural': 'Blog Galleries',
            },
        ),
    ]
