# Generated by Django 5.1.4 on 2025-01-05 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0013_alter_blogvisits_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogvisits',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='blog_module.blog', verbose_name='Blog'),
        ),
    ]
