# Generated by Django 5.1.4 on 2025-04-23 16:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0014_alter_blogvisits_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Text'),
        ),
    ]
