# Generated by Django 5.1.4 on 2025-04-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0015_alter_blog_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomments',
            name='subject',
        ),
    ]
