# Generated by Django 5.1.4 on 2024-12-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
