# Generated by Django 5.1.4 on 2025-01-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Position'),
        ),
    ]
