# Generated by Django 5.1.4 on 2025-01-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superauthor',
            field=models.BooleanField(default=False, verbose_name='Is Super Author'),
        ),
    ]
