# Generated by Django 5.1.4 on 2025-01-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Temporary Email'),
        ),
    ]
