# Generated by Django 5.1.4 on 2025-01-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_user_temp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax'),
        ),
    ]
