# Generated by Django 5.1.4 on 2025-01-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_user_fax'),
        ('product_module', '0012_productcomments_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='product_module.product', verbose_name='Favorite Products'),
        ),
    ]
